server:
  port: 8084

Spring:
  application:
    name: USER-SERVICE


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: 	org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
